language: python

dist: xenial

python:
  - "3.6"

services:
  - docker

before_install:
  - pip install neurodocker
  - neurodocker generate docker 
    --base=neurodebian:buster-non-free --pkg-manager=apt \
    --install apt-utils git ssh python3-pip gcc python3-setuptools python3-dev python3-wheel \
    file \
    graphviz \
    --run 'pip3 install git+https://github.com/gpiantoni/intraop.git#egg=intraop[test]' \
    --user neuro \
    --env USER=neuro \
    --env PATH='${PATH}:/home/neuro/.local/bin:/home/neuro/docker' \
    > dockerfile

  # use the same user UID for travis / docker
  - sed -i "s/useradd/& -u $UID/" dockerfile

  - cat dockerfile

install:
  - docker build --tag gpiantoni/neurotools:$TRAVIS_TAG .

script:
  - docker run 
    -i -t --rm 
    -v $TRAVIS_BUILD_DIR:/home/neuro 
    -w /home/neuro 
    --user neuro 
    gpiantoni/neurotools:$TRAVIS_TAG
    python3 -c "import intraop; print(intraop); exit"

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push gpiantoni/neurotools:$TRAVIS_TAG

notifications:
  email: false
